### ISSUE TITLE
Repository is not in Pypi

### ISSUE THREAD

**Issue by NOemDot** [jorgeajimenezl/animeflv-api#2]
Hi, I was trying to use the API in repl.it, but I could not make it work, same goes with the pip command.
Could the repository be uploaded to Pypi to make it more accessible?

**Comment by jorgeajimenezl** [comment]
Ok, I already uploaded the package to PyPI, anyway I don't make sure it works (**I think animeflv.net changed the way it shows the pages**) since I have left the development of it, I will probably continue to maintain it later. Sorry for the problems caused
