### ISSUE TITLE
Feature request: get new animes in animeflv

### ISSUE THREAD

**Issue by dmtzs** [jorgeajimenezl/animeflv-api#6]
Could be a function that can be able to get the new animes that are released in the web page?

**Comment by jorgeajimenezl** [comment]
@dmtzs I'll try to implement this when I have free time, sorry for the wait, but I'm in college

**Comment by jorgeajimenezl** [comment]
@dmtzs Hi, there's a new version (https://github.com/jorgeajimenezl/animeflv-api/commit/cc7ba51339c28fbd8b91c0bb41827e07b995d356) that adds this feature
